import {describe,it,expect,vi} from 'vitest';
import {mkdtemp,writeFile,readFile,chmod,symlink,stat,access,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import{join}from'node:path';
import{connect}from'@thenavidm/slipway/testing';
import{loadConfig,type Config}from'../src/config.js';import{TeachableClient}from'../src/api/client.js';import{ALL_TOOLS,compileAll,validateArguments,visibleTools}from'../src/tools/index.js';import{createApp,TOOLS}from'../src/app.js';import native from'../src/tools/operations.json' with{type:'json'};
const env={TEACHABLE_API_KEY:'fixture-key-not-a-provider-secret',TEACHABLE_MIN_REQUEST_INTERVAL_MS:'0'};
const config=(extra:Record<string,string>={})=>loadConfig({...env,...extra});
const response=(data:unknown,status=200)=>new Response(status===204?null:JSON.stringify(data),{status});
function client(c=config(),data:unknown={nativeReceipt:true},status=200){const fetcher=vi.fn(async()=>response(data,status));return{c:new TeachableClient(c,fetcher as typeof fetch),fetcher};}
const tool=(name:string)=>ALL_TOOLS.find(t=>t.name===name)!;
async function run(name:string,args:Record<string,any>,c:TeachableClient){validateArguments(tool(name),args);return tool(name).handler(args,c);}
// The real Slipway server with an injected client, so the network stays a stub. A call to a
// hidden tool is a protocol error rather than a tool result; both are refusals a client sees.
async function protocol(extra:Record<string,string>,api:TeachableClient){const app=createApp({context:()=>({config:config(extra),client:api})}),mcp=await connect(app,{env:{...env,...extra}});return{sdk:{listTools:async()=>({tools:await mcp.listTools()}),callTool:async({name,arguments:args}:{name:string;arguments:Record<string,unknown>})=>{try{return await mcp.callTool(name,args);}catch(e){return{isError:true,content:[{type:'text',text:(e as Error).message}]};}}},close:()=>mcp.close()};}
const appFor=(extra:Record<string,string>={})=>createApp({context:()=>({config:config(extra),client:client(config(extra)).c})});
const coursePage=(ids:number[],page=1,totalPages=1,size=2)=>({courses:ids.map(id=>({id})),meta:{page,per_page:size,number_of_pages:totalPages}});
const privateDir=()=>mkdtemp(join(tmpdir(),'teachable-behavior-'));

describe('discovery and effects share the real protocol',()=>{
 it.each([[{},26,19],[{TEACHABLE_ENABLE_V2:'1'},123,64]])('exposes explicit beta policy with %j',async(extra,total,reads)=>{const c=config(extra),api=client(c),p=await protocol(extra,api.c);try{expect((await p.sdk.listTools()).tools).toHaveLength(total);expect(visibleTools({...c,readOnly:true})).toHaveLength(reads);expect(api.fetcher).not.toHaveBeenCalled();}finally{await p.close();}});
 it('refuses a hidden beta direct call before network',async()=>{const api=client(),p=await protocol({},api.c);try{expect((await p.sdk.callTool({name:'v2_list_courses',arguments:{}})).isError).toBe(true);expect(api.fetcher).not.toHaveBeenCalled();}finally{await p.close();}});
 it.each(['mcp','cli'] as const)('refuses every effect without confirmation on %s',async surface=>{const beta={TEACHABLE_ENABLE_V2:'1'},app=appFor(beta);for(const t of TOOLS.filter(t=>t.risk!=='read'))await expect(app.run(t,{},{surface,env:{...env,...beta}})).rejects.toThrow(surface==='cli'?'--confirm':'confirm: true');});
 it('read-only directly refuses a hidden native write',async()=>{const c=config({TEACHABLE_READ_ONLY:'1'}),api=client(c),p=await protocol({TEACHABLE_READ_ONLY:'1'},api.c);try{expect((await p.sdk.callTool({name:'create_enrollment',arguments:{course_id:7,user_id:9,confirm:true}})).isError).toBe(true);expect(api.fetcher).not.toHaveBeenCalled();}finally{await p.close();}});
 it('effects disabled refuses confirmation too',async()=>{const off={TEACHABLE_ALLOW_DESTRUCTIVE:'0'},app=appFor(off);await expect(app.run(TOOLS.find(t=>t.name==='create_enrollment')!,{course_id:7,user_id:9},{surface:'mcp',confirmed:true,env:{...env,...off}})).rejects.toThrow('unavailable');});
 it('allows a deliberately confirmed native enrollment and preserves empty204 receipt',async()=>{const api=client(config(),null,204),p=await protocol({},api.c);try{const r=await p.sdk.callTool({name:'create_enrollment',arguments:{course_id:7,user_id:9,confirm:true}});expect(r.isError).toBeUndefined();expect(api.fetcher).toHaveBeenCalledOnce();const [url,request]=api.fetcher.mock.calls[0] as unknown as [URL,RequestInit];expect(String(url)).toBe('https://developers.teachable.com/v1/enroll');expect(JSON.parse(request.body as string)).toEqual({course_id:7,user_id:9});}finally{await p.close();}});
});

describe('native routing, profiles and bounded transport',()=>{
 it('compiles every input, body and receipt schema with the native validator',()=>expect(compileAll()).toBeGreaterThan(ALL_TOOLS.length));
 it('defaults discovery to no credential requirement',()=>expect(visibleTools(loadConfig({}))).toHaveLength(26));
 it('never inherits a global credential into named profiles',async()=>{const c=config({TEACHABLE_ACCOUNTS:'[{"name":"school"}]'}),api=client(c);await expect(run('list_courses',{},api.c)).rejects.toThrow('No valid API key');expect(api.fetcher).not.toHaveBeenCalled();});
 it.each([{TEACHABLE_API_KEY:'x',TEACHABLE_CREDENTIALS_FILE:'/private/file'},{TEACHABLE_API_VERSION:'2'},{TEACHABLE_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'},{TEACHABLE_ACCOUNTS:'[{"name":"a","password":"x"}]'}])('rejects ambiguous/invalid profile %j',extra=>expect(()=>config(extra)).toThrow());
 it('v1 and v2 profiles never fallback to each other',async()=>{const c=config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),api=client(c);await expect(run('list_courses',{},api.c)).rejects.toThrow('version');await expect(api.c.request('GET','/v1/courses')).rejects.toThrow('version');expect(api.fetcher).not.toHaveBeenCalled();});
 it('routes beta lecture listing only to the documented beta route',async()=>{const c=config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),api=client(c);await run('v2_list_lectures_for_course',{course_id:'7'},api.c);expect(String(api.fetcher.mock.calls[0]![0])).toBe('https://developers.teachable.com/v2/products/courses/7/lectures');});
 it('retains documented native pricing root and filters',async()=>{const api=client();await run('list_pricing_plans',{page:2,per:5},api.c);expect(String(api.fetcher.mock.calls[0]![0])).toBe('https://developers.teachable.com/v1/pricing_plans?page=2&per=5');});
 it('rejects invented enrollment pagination and user-name filters',()=>{expect(()=>validateArguments(tool('list_enrollments'),{course_id:7,page:1})).toThrow();expect(()=>validateArguments(tool('list_users'),{name:'Example'})).toThrow();});
 it.each(['create_webhook','delete_webhook','list_lectures'])('does not ship undocumented legacy %s',name=>expect(ALL_TOOLS.some(t=>t.name===name)).toBe(false));
 it.each(['/v1/users/../courses','/v1/users/%2Fother','//evil.example/v1/courses','/v1/courses?apiKey=bad'])('rejects arbitrary method/path %s before credential use',async path=>{const api=client();await expect(api.c.request('GET',path)).rejects.toThrow();expect(api.fetcher).not.toHaveBeenCalled();});
 it('sends only apiKey authentication to fixed host with redirects refused',async()=>{const api=client();await run('list_courses',{},api.c);const [url,init]=api.fetcher.mock.calls[0] as unknown as [URL,RequestInit];expect(url.host).toBe('developers.teachable.com');expect(init.redirect).toBe('error');expect(init.headers).toMatchObject({apiKey:env.TEACHABLE_API_KEY});expect(init.headers).not.toHaveProperty('Authorization');});
 it.each([401,403,404,429,500])('preserves HTTP%s and never retries',async status=>{const api=client(config(),{message:env.TEACHABLE_API_KEY},status);await expect(run('list_courses',{},api.c)).rejects.toMatchObject({status});expect(api.fetcher).toHaveBeenCalledOnce();try{await run('list_courses',{},api.c);}catch(e){expect((e as Error).message).not.toContain(env.TEACHABLE_API_KEY);}});
 it('refuses unexpected success or empty receipt',async()=>{await expect(run('list_courses',{},client(config(),{},202).c)).rejects.toThrow('Unexpected');const api=client();api.fetcher.mockImplementationOnce(async()=>new Response(null,{status:200}));await expect(run('list_courses',{},api.c)).rejects.toThrow('Missing native receipt');});
 it('does not retry network errors or echo fetch exceptions',async()=>{const api=client();api.fetcher.mockRejectedValueOnce(Error('fixture-private-detail'));await expect(run('list_courses',{},api.c)).rejects.toThrow('Outcome may be unknown');expect(api.fetcher).toHaveBeenCalledOnce();});
 it('bounds native request and response bytes',async()=>{const api=client();await expect(api.c.request('POST','/v1/users',[],{email:'x'.repeat(1048577)})).rejects.toThrow('1 MiB');expect(api.fetcher).not.toHaveBeenCalled();api.fetcher.mockImplementationOnce(async()=>new Response('x'.repeat(5*1048576+1)));await expect(run('list_courses',{},api.c)).rejects.toThrow('5 MiB');});
 it('reads owner-private key file without exposing source path/key in profile discovery',async()=>{const dir=await privateDir();try{const path=join(dir,'key.json');await writeFile(path,JSON.stringify({api_key:'fixture-file-key'}),{mode:0o600});const api=client(loadConfig({TEACHABLE_CREDENTIALS_FILE:path,TEACHABLE_MIN_REQUEST_INTERVAL_MS:'0'}));await run('list_courses',{},api.c);expect(JSON.stringify(await run('list_accounts',{},api.c))).not.toContain(path);expect(api.c.redactText('fixture-file-key')).toBe('[redacted]');}finally{await rm(dir,{recursive:true,force:true});}});
 it('refuses a symlink key file before network',async()=>{const dir=await privateDir();try{const target=join(dir,'target');await writeFile(target,'{"api_key":"fixture"}',{mode:0o600});const path=join(dir,'link');await symlink(target,path);const api=client(loadConfig({TEACHABLE_CREDENTIALS_FILE:path}));await expect(run('list_courses',{},api.c)).rejects.toThrow('private credential');expect(api.fetcher).not.toHaveBeenCalled();}finally{await rm(dir,{recursive:true,force:true});}});
});

describe('private native bodies and consent',()=>{
 it('create user uses flat native fields, not legacy wrapper or role',async()=>{const api=client(config(),{id:7,email:'student@example.invalid',name:'Example',role:'student',last_sign_in_ip:null,courses:[],tags:[]},201);await run('create_user',{email:'student@example.invalid',name:'Example'},api.c);expect(JSON.parse((api.fetcher.mock.calls[0] as unknown as [URL,RequestInit])[1].body as string)).toEqual({email:'student@example.invalid',name:'Example'});expect(()=>validateArguments(tool('create_user'),{email:'x',role:'owner'})).toThrow();});
 it('has no password flag and refuses inline password body',async()=>{const api=client();expect(tool('create_user').inputSchema.properties).not.toHaveProperty('password');await expect(run('create_user',{payload:{email:'student@example.invalid',password:'fixture-user-password'}},api.c)).rejects.toThrow('payload_file');expect(api.fetcher).not.toHaveBeenCalled();expect(api.c.redactText('fixture-user-password')).toBe('[redacted]');});
 it('accepts a private payload file and redacts echoed password',async()=>{const dir=await privateDir();try{const file=join(dir,'user.json');await writeFile(file,JSON.stringify({email:'student@example.invalid',password:'fixture-user-password'}),{mode:0o600});const api=client(config(),{message:'fixture-user-password',password:'fixture-user-password'},201);const result=await run('create_user',{payload_file:file},api.c);expect(JSON.stringify(result)).not.toContain('fixture-user-password');}finally{await rm(dir,{recursive:true,force:true});}});
 it('forbids mixing payload with body flags',async()=>{const api=client();await expect(run('create_user',{email:'x',payload:{email:'y'}},api.c)).rejects.toThrow('mix');expect(api.fetcher).not.toHaveBeenCalled();});
 it('requires explicit student marketing decision and native revenue share',async()=>{const api=client(config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),{},201);for(const payload of [{name:'Example',email:'student@example.invalid',role:'student'},{name:'Example',email:'author@example.invalid',role:'author',author_revenue_share:1.2},{name:'Example',email:'owner@example.invalid',role:'owner',affiliate_revenue_share:0.2}])await expect(run('v2_create_user',{payload},api.c)).rejects.toThrow();expect(api.fetcher).not.toHaveBeenCalled();await run('v2_create_user',{name:'Example',email:'student@example.invalid',role:'student',allow_marketing_emails:false},api.c);expect(JSON.parse((api.fetcher.mock.calls[0] as unknown as [URL,RequestInit])[1].body as string).allow_marketing_emails).toBe(false);});
});

describe('reviewed effects and partial outcomes',()=>{
 const tasks=[{tool:'create_enrollment',arguments:{course_id:7,user_id:9}},{tool:'unenroll_user',arguments:{course_id:8,user_id:9}}];
 it('preview validates all requests without credential loading or network',async()=>{const api=client(loadConfig({TEACHABLE_ACCOUNTS:'[{"name":"school"}]'}));const r=await run('preview_school_batch',{tasks},api.c) as any;expect(r.calls[0].path).toBe('/v1/enroll');expect(r.providerValidated).toBe(false);expect(r.apiVersion).toBe('1');expect(api.fetcher).not.toHaveBeenCalled();});
 it('review binds order and requests before first network call',async()=>{const api=client();const preview=await run('preview_school_batch',{tasks},api.c) as any;await expect(run('submit_school_batch',{tasks:[...tasks].reverse(),review_sha256:preview.reviewSha256},api.c)).rejects.toThrow('hash');expect(api.fetcher).not.toHaveBeenCalled();});
 it('stops at first failure with known receipts and no retries/rollback',async()=>{const api=client(config(),null,204);api.fetcher.mockImplementationOnce(async()=>response(null,204)).mockImplementationOnce(async()=>response({message:'failure'},429));const more=[...tasks,tasks[0]!],p=await run('preview_school_batch',{tasks:more},api.c) as any;try{await run('submit_school_batch',{tasks:more,review_sha256:p.reviewSha256},api.c);throw Error('expected failure');}catch(e){expect(e).toMatchObject({status:429});const r=JSON.parse((e as Error).message);expect(r.knownResults).toHaveLength(1);expect(r.unattemptedIndices).toEqual([2]);}expect(api.fetcher).toHaveBeenCalledTimes(2);});
 it('rejects all mutable payload files and private outputs in batches',async()=>{const api=client();await expect(run('preview_school_batch',{tasks:[{tool:'create_user',arguments:{payload_file:'/private/user.json'}}]},api.c)).rejects.toThrow('mutable');expect(api.fetcher).not.toHaveBeenCalled();});
 it('prevalidates later invalid effects before executing earlier effects',async()=>{const api=client();await expect(run('preview_school_batch',{tasks:[tasks[0],{tool:'unenroll_user',arguments:{user_id:9}}]},api.c)).rejects.toThrow();expect(api.fetcher).not.toHaveBeenCalled();});
});

describe('private export and upload credentials',()=>{
 it('exports bounded native v1 pages with exact offset continuation and0600',async()=>{const dir=await privateDir();try{const file=join(dir,'export.json'),api=client(config(),coursePage([7,8]));const r=await run('export_resources',{operation:'list_courses',arguments:{per:2},max_items:1,output_file:file},api.c) as any;expect(r.items).toBe(1);expect(r.continuation).toMatchObject({arguments:{page:1,per:2},start_offset:1});expect(JSON.parse(await readFile(file,'utf8')).data).toEqual([{id:7}]);if(process.platform!=='win32')expect((await stat(file)).mode&0o777).toBe(0o600);}finally{await rm(dir,{recursive:true,force:true});}});
 it('resumes inside a page without dropping remaining rows',async()=>{const dir=await privateDir();try{const api=client(config(),coursePage([7,8])),file=join(dir,'export.json');const r=await run('export_resources',{operation:'list_courses',arguments:{page:1,per:2},start_offset:1,output_file:file},api.c) as any;expect(r.completeWithinRequestedFilters).toBe(true);expect(JSON.parse(await readFile(file,'utf8')).data).toEqual([{id:8}]);}finally{await rm(dir,{recursive:true,force:true});}});
 it('uses beta page/per_page/data/meta without stable fallback',async()=>{const dir=await privateDir();try{const api=client(config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),{data:[{id:7}],meta:{page:1,per_page:2,total_pages:1}});const r=await run('export_resources',{operation:'v2_list_courses',arguments:{per_page:2},output_file:join(dir,'export.json')},api.c) as any;expect(r.completeWithinRequestedFilters).toBe(true);expect(String(api.fetcher.mock.calls[0]![0])).toContain('/v2/products/courses?page=1&per_page=2');}finally{await rm(dir,{recursive:true,force:true});}});
 it('refuses overwrite before network and cleans failed new exports',async()=>{const dir=await privateDir();try{const file=join(dir,'existing');await writeFile(file,'keep');const api=client();await expect(run('export_resources',{operation:'list_courses',output_file:file},api.c)).rejects.toThrow('exclusively');expect(api.fetcher).not.toHaveBeenCalled();expect(await readFile(file,'utf8')).toBe('keep');const fresh=join(dir,'fresh');await expect(run('export_resources',{operation:'list_courses',output_file:fresh},api.c)).rejects.toThrow('pagination');await expect(access(fresh)).rejects.toThrow();}finally{await rm(dir,{recursive:true,force:true});}});
 it('excludes list endpoints without reviewed page contracts',()=>expect(tool('export_resources').inputSchema.properties.operation.enum).not.toContain('list_enrollments'));
 it('saves signed upload credentials exclusively; ordinary output omits them',async()=>{const dir=await privateDir();try{const cfg=config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),api=client(cfg,{data:{upload_url:'https://storage.example.invalid?signature=fixture',upload_method:'POST',upload_headers:{'Content-Type':'multipart/form-data'},url:'https://cdn.example.invalid/file',expires:'2026-10-05T00:00:00Z',upload_id:'00000000-0000-4000-8000-000000000000'}},201),file=join(dir,'receipt.json');const r=await run('v2_create_pre_signed_upload_credentials',{payload:{type:'lecture',id:7,purpose:'attachment',extension:'pdf'},output_file:file},api.c);expect(JSON.stringify(r)).not.toContain('signature');expect(JSON.parse(await readFile(file,'utf8')).data.upload_url).toContain('signature');expect(api.fetcher).toHaveBeenCalledOnce();}finally{await rm(dir,{recursive:true,force:true});}});
 it('invalid upload receipt deletes private output and does not retry',async()=>{const dir=await privateDir();try{const api=client(config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),{data:{upload_url:'https://example.invalid'}},201),file=join(dir,'receipt.json');await expect(run('v2_create_pre_signed_upload_credentials',{payload:{type:'lecture',id:7,purpose:'attachment',extension:'pdf'},output_file:file},api.c)).rejects.toThrow('Invalid native upload');await expect(access(file)).rejects.toThrow();expect(api.fetcher).toHaveBeenCalledOnce();}finally{await rm(dir,{recursive:true,force:true});}});
 it('contracts preserve every reviewed native method/path and unique names',()=>{expect(native).toHaveLength(118);expect(new Set(native.map(o=>o.name)).size).toBe(118);expect(native.filter(o=>o.apiVersion==='1')).toHaveLength(21);expect(native.filter(o=>o.apiVersion==='2')).toHaveLength(97);});
});

describe('native coupon constraints beyond JSON types',()=>{
 const coupon={code:'EXAMPLE',name:'Example',duration_kind:'once'};
 it.each([{...coupon},{...coupon,scope_type:'all_products',pricing_plan_id:7},{...coupon,product_type:'course'},{...coupon,scope_type:'all_products',duration_kind:'repeating'},{...coupon,scope_type:'all_products',discount_in_months:3}])('rejects invalid native coupon scope/duration before network',async payload=>{const api=client(config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),{},201);await expect(run('v2_create_coupon',{payload},api.c)).rejects.toThrow();expect(api.fetcher).not.toHaveBeenCalled();});
 it('requires new-payment fields when selecting product-scoped shape',async()=>{const api=client(config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}),{},201);await expect(run('v2_create_coupon',{payload:{...coupon,product_type:'course',product_id:7}},api.c)).rejects.toThrow('new-payments');expect(api.fetcher).not.toHaveBeenCalled();});
 it('refuses partial product query pair or overlong date range',async()=>{const api=client(config({TEACHABLE_ENABLE_V2:'1',TEACHABLE_API_VERSION:'2'}));await expect(run('v2_list_coupons',{product_type:'course'},api.c)).rejects.toThrow('paired');await expect(run('v2_list_coupons',{created_after:'2026-01-01T00:00:00Z',created_before:'2026-10-04T00:00:00Z'},api.c)).rejects.toThrow('90days');expect(api.fetcher).not.toHaveBeenCalled();});
});
